# Generated by Django 5.1.5 on 2025-01-25 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_bot_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='name',
            field=models.CharField(default='Default Name', max_length=255),
        ),
    ]
