# Generated by Django 5.1.5 on 2025-01-25 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_bot_api', '0002_customuser_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='name',
        ),
    ]
