# Generated by Django 5.1.5 on 2025-01-25 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_bot_api', '0004_customuser_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
