# Generated by Django 5.1.5 on 2025-01-28 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_bot_api', '0005_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
    ]
