# Generated by Django 5.1.5 on 2025-01-28 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_bot_api', '0006_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='name',
        ),
    ]
