# Generated by Django 5.1.5 on 2025-02-10 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_bot_api', '0009_remove_customuser_name_alter_customuser_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddCompanies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='company_logo/')),
                ('company_email', models.EmailField(max_length=254, unique=True)),
                ('company_phone', models.CharField(max_length=15)),
                ('industry_type', models.CharField(max_length=255)),
                ('district', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('website_url', models.URLField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
    ]
