# Generated by Django 5.1.5 on 2025-02-10 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_bot_api', '0010_addcompanies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addcompanies',
            name='website_url',
            field=models.CharField(max_length=255),
        ),
    ]
