# Generated by Django 5.1.5 on 2025-02-10 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_bot_api', '0011_alter_addcompanies_website_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addcompanies',
            name='company_logo',
        ),
    ]
