# Generated by Django 5.1.5 on 2025-02-10 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_bot_api', '0013_addcompanies_company_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addcompanies',
            name='company_logo',
            field=models.ImageField(blank=True, default='company_logo', upload_to='company_logo/'),
        ),
    ]
