# Generated by Django 5.1.5 on 2025-02-10 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_bot_api', '0015_alter_addcompanies_company_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=255)),
                ('required_skills', models.CharField(max_length=255)),
                ('experience', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('job_type', models.CharField(max_length=255)),
                ('salary_range', models.CharField(max_length=255)),
                ('job_description', models.TextField()),
                ('application_deadline', models.CharField(max_length=255)),
                ('company_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ai_bot_api.addcompanies')),
            ],
        ),
    ]
