# Generated by Django 5.1.1 on 2025-02-22 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_bot_api', '0018_jobapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='addjob',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
