# Generated by Django 5.1.1 on 2025-02-22 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_bot_api', '0019_addjob_created_at_jobapplication_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addjob',
            name='created_at',
            field=models.DateField(auto_now_add=True, default='2024-07-05'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='created_at',
            field=models.DateField(auto_now_add=True, default='2024-07-05'),
            preserve_default=False,
        ),
    ]
