# Generated by Django 5.1.1 on 2025-02-22 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_bot_api', '0020_alter_addjob_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('rejected', 'rejected'), ('shortlisted', 'shortlisted'), ('technial_interview', 'technial_interview'), ('technial_interview_rejected', 'technial_interview_rejected'), ('hr_interview', 'hr_interview'), ('hr_interview_rejected', 'hr_interview_rejected'), ('hr_interview', 'hr_interview'), ('hr_interview_rejected', 'hr_interview_rejected'), ('hired', 'hired')], default='pending', max_length=125),
        ),
    ]
