# Generated by Django 5.1.1 on 2025-02-24 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_bot_api', '0022_examscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='score',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('rejected', 'rejected'), ('shortlisted', 'shortlisted'), ('technial_interview', 'technial_interview'), ('technial_interview_rejected', 'technial_interview_rejected'), ('hr_interview', 'hr_interview'), ('hr_interview_rejected', 'hr_interview_rejected'), ('hired', 'hired'), ('interview_completed', 'interview_completed')], default='pending', max_length=125),
        ),
    ]
