# Generated by Django 5.1.1 on 2025-02-25 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_bot_api', '0023_jobapplication_score_alter_jobapplication_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('rejected', 'rejected'), ('shortlisted', 'shortlisted'), ('technical_interview', 'technical_interview'), ('technical_interview_completed', 'technical_interview_completed'), ('technical_interview_rejected', 'technical_interview_rejected'), ('hr_interview', 'hr_interview'), ('hr_interview_rejected', 'hr_interview_rejected'), ('hired', 'hired'), ('interview_completed', 'interview_completed')], default='pending', max_length=125),
        ),
    ]
